### ISSUE TITLE
Potential fragment directive parsing bugs

### ISSUE THREAD

**Issue by eligrey** [tomayac/link-to-media#2]
[This fragment directive parsing code](https://github.com/tomayac/link-to-media/blob/04dbf306d746e5eb5ecd5e17be920d96ed9d230f/polyfill/scroll-to.js#L29-L38) looks flimsy and doesn't correctly handle multiple directives. The selector validation logic is fine but the code which extracts the fragment directives seems problematic.

Feel free to copy [this getFragmentDirectives() function](https://go.eligrey.com/t/getFragmentDirectives.js). I am dedicating that entire code snippet block to the public domain.

**Comment by tomayac** [comment]
Do you want to PR this in? Asking since you were interested in contributing on Twitter.

**Comment by eligrey** [comment]
Yeah I can do that later ~~today~~ this weekend 👍

**Comment by eligrey** [comment]
I ended up quite busy today. I'll definitely try to contribute this weekend though

**Comment by eligrey** [comment]
Oh I hadn't realized that this syntax was not compatible with the `URLSearchParams` parser. Has there been any discussion about aiming to make fragment directives follow a similar syntax to search params?

To re-use the `getFragmentDirectives()` utility I wrote, this spec would have to use a URL-encoded key-value pairing. I can look into improving the existing code where possible later, as I'm definitely interested in helping get this project running.

**Comment by tomayac** [comment]
In the case of media, the aim was to reuse the existing syntax of WebAnnotations. See https://github.com/WICG/scroll-to-text-fragment/blob/main/EXTENSIONS.md#proposed-solution and https://www.w3.org/TR/2017/NOTE-selectors-states-20170223/#FragmentSelector_frag.
